name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full git history

      - uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"
          cache: "npm"

      - name: Set npm fetch timeout
        run: npm config set fetch-timeout 60000

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies with retry
        run: |
          for i in 1 2 3; do
            npm ci && break || {
              echo "Retrying npm ci ($i)..."
              sleep 10
            }
          done

      - name: Install nx globally
        run: npm install -g nx@20.3.0

      - name: Check formatting
        run: npm run format -- --check

      - name: Run affected commands
        run: npx nx affected -t lint test build --base=origin/main --head=HEAD
