name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Install Cypress
      - name: Install Cypress
        run: npx cypress install

      # Setup Nx
      - uses: nrwl/nx-set-shas@v4

      # Lint
      - name: Lint
        run: npx nx affected -t lint
        continue-on-error: true

      # Test
      - name: Test
        run: npx nx affected -t test
        continue-on-error: true

      # Build
      - name: Build
        run: npx nx affected -t build

      # E2E Tests
      - name: E2E Tests
        run: npx nx affected -t e2e
        continue-on-error: true

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: dist
          path: dist/
          retention-days: 7

      # Cache build output
      - name: Cache build output
        uses: actions/cache@v4
        if: success()
        with:
          path: |
            dist/
            .nx/cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
